# Generated by Django 5.2 on 2025-12-17 12:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название олимпиады')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('registration_start', models.DateTimeField(verbose_name='Начало регистрации')),
                ('registration_end', models.DateTimeField(verbose_name='Окончание регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('max_subjects_per_student', models.PositiveIntegerField(default=1, verbose_name='Максимум предметов на студента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиады',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Студенческий билет')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Длительность (минуты)')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Максимальный балл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.olympiad', verbose_name='Олимпиада')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiads', to='app.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет олимпиады',
                'verbose_name_plural': 'Предметы олимпиады',
                'ordering': ['olympiad', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен сессии')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Номер попытки')),
                ('status', models.CharField(choices=[('not_started', 'Не начата'), ('in_progress', 'В процессе'), ('paused', 'Приостановлена'), ('completed', 'Завершена'), ('expired', 'Истекла'), ('abandoned', 'Прервана'), ('submitted', 'Отправлена на проверку')], default='not_started', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('is_paused', models.BooleanField(default=False, verbose_name='Приостановлена')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Время приостановки')),
                ('pause_count', models.PositiveIntegerField(default=0, verbose_name='Количество пауз')),
                ('total_pause_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Общая длительность пауз (секунды)')),
                ('current_question_index', models.PositiveIntegerField(default=0, verbose_name='Текущий вопрос (индекс)')),
                ('questions_answered_count', models.PositiveIntegerField(default=0, verbose_name='Количество отвеченных вопросов')),
                ('question_order', models.JSONField(blank=True, default=list, verbose_name='Порядок вопросов (JSON)')),
                ('is_random_order', models.BooleanField(default=False, verbose_name='Случайный порядок вопросов')),
                ('question_timings', models.JSONField(blank=True, default=dict, verbose_name='Время на вопросы (JSON)')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Потрачено времени (секунды)')),
                ('checkpoint_data', models.JSONField(blank=True, default=dict, verbose_name='Данные чекина (JSON)')),
                ('last_checkpoint_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний чекин')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Набранные баллы')),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Максимальный балл')),
                ('penalty_points', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Штрафные баллы')),
                ('bonus_points', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонусные баллы')),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговый балл')),
                ('answer_changes_count', models.PositiveIntegerField(default=0, verbose_name='Количество изменений ответов')),
                ('questions_skipped_count', models.PositiveIntegerField(default=0, verbose_name='Количество пропущенных вопросов')),
                ('questions_reviewed_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотренных вопросов')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('browser_fingerprint', models.CharField(blank=True, max_length=255, verbose_name='Отпечаток браузера')),
                ('allow_back_navigation', models.BooleanField(default=True, verbose_name='Разрешена навигация назад')),
                ('show_correct_answers', models.BooleanField(default=False, verbose_name='Показывать правильные ответы')),
                ('is_proctored', models.BooleanField(default=False, verbose_name='Прокторинг включен')),
                ('suspicious_activities', models.JSONField(blank=True, default=list, verbose_name='Подозрительная активность (JSON)')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='Количество предупреждений')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные метаданные (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('olympiad_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='app.olympiadsubject', verbose_name='Предмет олимпиады')),
            ],
            options={
                'verbose_name': 'Сессия экзамена',
                'verbose_name_plural': 'Сессии экзаменов',
                'ordering': ['-started_at', '-attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('description', models.TextField(blank=True, verbose_name='Дополнительное описание')),
                ('scoring_method', models.CharField(choices=[('weighted_sum', 'Взвешенная сумма ответов'), ('proportional', 'Пропорциональное распределение'), ('threshold', 'Пороговая система'), ('combinatorial', 'Комбинаторная оценка'), ('adaptive', 'Адаптивная оценка')], default='weighted_sum', max_length=20, verbose_name='Метод оценки')),
                ('base_points', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Базовые баллы')),
                ('max_points', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Максимальные баллы')),
                ('min_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Минимальные баллы')),
                ('difficulty_level', models.CharField(choices=[('basic', 'Базовый'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Экспертный')], default='intermediate', max_length=20, verbose_name='Уровень сложности')),
                ('estimated_time_seconds', models.PositiveIntegerField(default=60, verbose_name='Оценочное время (секунды)')),
                ('required_answers_count', models.PositiveIntegerField(default=1, verbose_name='Требуемое количество ответов')),
                ('allow_partial_selection', models.BooleanField(default=True, verbose_name='Разрешена частичная выборка')),
                ('shuffle_answers', models.BooleanField(default=False, verbose_name='Перемешивать варианты ответов')),
                ('penalty_for_wrong', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Штраф за неправильный ответ')),
                ('hint_available', models.BooleanField(default=False, verbose_name='Доступна подсказка')),
                ('hint_text', models.TextField(blank=True, verbose_name='Текст подсказки')),
                ('hint_cost_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Стоимость подсказки (баллы)')),
                ('answer_combination_rules', models.JSONField(blank=True, default=dict, verbose_name='Правила комбинаций ответов (JSON)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('depends_on_questions', models.ManyToManyField(blank=True, related_name='dependent_questions', to='app.question', verbose_name='Зависит от вопросов')),
                ('olympiad_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.olympiadsubject', verbose_name='Предмет олимпиады')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['olympiad_subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('correctness_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Вес правильности (-1.0 до 1.0)')),
                ('partial_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Частичные баллы')),
                ('penalty_weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Вес штрафа')),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение ответа')),
                ('difficulty_modifier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Модификатор сложности')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет отображения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('conflicts_with_answers', models.ManyToManyField(blank=True, to='app.answer', verbose_name='Конфликтует с ответами')),
                ('requires_other_answers', models.ManyToManyField(blank=True, related_name='required_by_answers', to='app.answer', verbose_name='Требует другие ответы')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['question', 'priority', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий балл')),
                ('max_possible_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Максимально возможный балл')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент выполнения (%)')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.olympiad', verbose_name='Олимпиада')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['-total_score', 'completed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Заработанные баллы')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='app.examsession', verbose_name='Сессия экзамена')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='app.question', verbose_name='Вопрос')),
                ('selected_answers', models.ManyToManyField(blank=True, related_name='student_selections', to='app.answer', verbose_name='Выбранные ответы')),
            ],
            options={
                'verbose_name': 'Ответ студента',
                'verbose_name_plural': 'Ответы студентов',
                'ordering': ['question__order'],
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.olympiad', verbose_name='Олимпиада')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subjects', models.ManyToManyField(related_name='student_registrations', to='app.subject', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Регистрация студента',
                'verbose_name_plural': 'Регистрации студентов',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='app.studentregistration', verbose_name='Регистрация'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['olympiad_subject', 'difficulty_level'], name='app_questio_olympia_6ae360_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order'], name='app_questio_order_e32175_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'correctness_weight'], name='app_answer_questio_dd6542_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'olympiad')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('exam_session', 'question')},
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['session_token'], name='app_examses_session_304591_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['student', 'olympiad_subject'], name='app_examses_student_08be39_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status', 'started_at'], name='app_examses_status_972842_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('student', 'olympiad_subject', 'registration', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together={('student', 'olympiad')},
        ),
        migrations.AlterUniqueTogether(
            name='olympiadsubject',
            unique_together={('olympiad', 'subject')},
        ),
    ]
