# Generated by Django 5.2 on 2025-12-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='status',
        ),
    ]
